using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace proyecto_cafe_una_backend.Migrations
{
    /// <inheritdoc />
    public partial class AddRegistrosPendientes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS registros_pendientes (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Token" character varying(20) NOT NULL,
                    "Correo" character varying(200) NOT NULL,
                    "Nombre" character varying(200) NOT NULL,
                    "PasswordHash" character varying(500) NOT NULL,
                    "ExpiraEnUtc" timestamp with time zone NOT NULL,
                    "Usado" boolean NOT NULL,
                    CONSTRAINT "PK_registros_pendientes" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_registros_pendientes_Correo"
                    ON registros_pendientes ("Correo");

                CREATE INDEX IF NOT EXISTS "IX_registros_pendientes_Token"
                    ON registros_pendientes ("Token");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "registros_pendientes");
        }
    }
}
